services:
  app:
    build: .
    container_name: pos-nest-app
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admindb
      - DB_PASSWORD=admindb
      - DB_NAME=pos
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
    # Uncomment if you want to mount local uploads for development
    # volumes:
    #   - ./uploads:/app/uploads
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_DB: pos
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: admindb
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - '5050:5050'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  data:
  pgadmin-data:
