// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFREsJ2aWnjBJe8aryJ-bvAhVM8U-9ojU',
    appId: '1:1091775425220:web:1199459d0489a151a7f791',
    messagingSenderId: '1091775425220',
    projectId: 'sip-sync-admin',
    authDomain: 'sip-sync-admin.firebaseapp.com',
    storageBucket: 'sip-sync-admin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8yakkoe-hPXePPL7EJOL_bMDaZ7EC6eE',
    appId: '1:1091775425220:android:1dc46a1b98b2b32da7f791',
    messagingSenderId: '1091775425220',
    projectId: 'sip-sync-admin',
    storageBucket: 'sip-sync-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9H3GDZPEpOxyaqTFgodNtrD89q6lvobs',
    appId: '1:1091775425220:ios:b292a82a12144250a7f791',
    messagingSenderId: '1091775425220',
    projectId: 'sip-sync-admin',
    storageBucket: 'sip-sync-admin.firebasestorage.app',
    iosBundleId: 'com.sipsync.client',
  );

}